// File generated by FlutterFire CLI (manually completed).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNpJ2v3WWPeGFOqmfIaywsfFIGOR9y3I',
    appId: '1:696999362975:web:fe33d2c6b7dcd98e5efdaa',
    messagingSenderId: '696999362975',
    projectId: 'cinemood-f7d53',
    authDomain: 'cinemood-f7d53.firebaseapp.com',
    storageBucket: 'cinemood-f7d53.firebasestorage.app',
    measurementId: 'G-YS7B7KL32J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3Mtb1S1zsUT3xbOYUKrzShY88ijGK5k',
    appId: '1:696999362975:android:16fa9c0557cc9e775efdaa',
    messagingSenderId: '696999362975',
    projectId: 'cinemood-f7d53',
    storageBucket: 'cinemood-f7d53.firebasestorage.app',
  );
}
